version: '3'
services:
  dev-db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
